---
- hosts: localhost
  become: true
  tasks:

  -  name: update the repository index
     when: ansible_distribution == "Ubuntu" 
     apt:
       update_cache=yes
  - name: install apache2 package
    when: ansible_distribution == "Ubuntu"
    apt:
      name: apache2
      state: latest
    
